dist: trusty
language: emacs
cache: apt
env:
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.2-travis
  - EVM_EMACS=emacs-git-snapshot-travis
matrix:
  fast-finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
install:
  - cask install
script:
  - echo $EMACS
  - export CURRENT_EMACS=${EMACS:-$(which emacs)}
  - make EMACS=${CURRENT_EMACS} info
  - make EMACS=${CURRENT_EMACS} build
